# Generated by Django 5.0 on 2024-02-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Slug',
            new_name='slug',
        ),
    ]
